package com.tim.room.model;

// Generated 2017-2-9 19:09:36 by Hibernate Tools 4.3.1

import java.util.UUID;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
    private UUID id;
    private String name;
    private String password;
    private String roomName;
    private String gender;

    public String getRoomName() {
        return roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public User() {
    }

    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }

}
